#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChGK.Droid.Resource", IsApplication=true)]

namespace ChGK.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int popup_hide = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int popup_show = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int GroupItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int MvxDropDownItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010008
			public const int MvxSource = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int footer = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int header = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public const int dark = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int light = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int light_light = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int light_light_light = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int light_light_transparent = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int light_transparent = 2131296258;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int default_padding = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int default_text_padding = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_transparent_chgk = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_check = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_check_off = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_check_off_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_check_on = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_check_on_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_default = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_default_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_default_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_default_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_default_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int divider_gradient = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int edit_text = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int expander_group = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int fastscroll_thumb = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int fastscroll_thumb_default = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int fastscroll_thumb_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_av_pause = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_av_play = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_av_replay = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_content_edit = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_content_new = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_content_paste = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_content_undo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_navigation_collapse = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_navigation_drawer = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_navigation_expand = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_navigation_refresh = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_navigation_refresh3 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int progress_bar = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int progress_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int progress_horizontal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int progress_primary = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int progress_secondary = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int selectable_background_chgk = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int splash = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int text_select_handle_left = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int text_select_handle_middle = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int text_select_handle_right = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int textfield_activated = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int textfield_default = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int textfield_disabled = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int textfield_disabled_focused = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int textfield_focused = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int undo_bar_bg = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int a1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int a2 = 2131099650;
			
			// aapt resource value: 0x7f060011
			public const int add_team = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int clear_results = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int content_frame = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int data = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int drawer = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int enter_results = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int items = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int refresh = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int start_timer = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int stop_timer = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int teams = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int time = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int undo_button = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int undo_message = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int viewPager = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EnterResultsView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FullImageView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomeView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int item_question = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int item_result_team = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int item_team = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int item_tour = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int item_tour_header = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int item_tournament = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LastAddedTournamentsView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int QuestionsView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int QuestionView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int RandomQuestionsView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SplashScreen = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TeamsView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int TourView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int undo_bar = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int menuitem = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int question = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int teamsview = 2131361794;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070005
			public const int add = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int cancel = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int clear_results = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int enter_results = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int no_teams = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int refresh = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int start = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int stop = 2131165188;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int ActionBar_Chgk = 2131230722;
			
			// aapt resource value: 0x7f08000b
			public const int Button_Chgk = 2131230731;
			
			// aapt resource value: 0x7f080001
			public const int ChGKTheme = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int CheckBox_Chgk = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int DialogChgk = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int DialogTitleTextAppearance = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int DialogWindowTitleChgk = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int EditTextChgk = 2131230729;
			
			// aapt resource value: 0x7f080004
			public const int ExpandableListView_Chgk = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int ListView_Chgk = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int ProgressBar_ChGK = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int ProgressBar_Chgk = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			// aapt resource value: 0x7f08000d
			public const int popup_fade_animation = 2131230733;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771976};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 1
			public const int MvxListView_GroupItemTemplate = 1;
			
			// aapt resource value: 2
			public const int MvxListView_MvxDropDownItemTemplate = 2;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			// aapt resource value: 4
			public const int MvxListView_footer = 4;
			
			// aapt resource value: 3
			public const int MvxListView_header = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
