#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ChGK.Droid.Resource", IsApplication=true)]

namespace ChGK.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int GroupItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int MvxDropDownItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int dark = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int light = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int light_light = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int light_light_light = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int light_light_transparent = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int default_padding = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int default_text_padding = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_transparent_chgk = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int divider_gradient = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int expander_group = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fastscroll_thumb = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fastscroll_thumb_default = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int fastscroll_thumb_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_av_pause = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_av_play = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_navigation_collapse = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_navigation_drawer = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_navigation_expand = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_navigation_refresh = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_navigation_refresh3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int progress_bar = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int selectable_background_chgk = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int splash = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int content_frame = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int drawer = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int items = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int refresh = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int start_timer = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int stop_timer = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int time = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int viewPager = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FullImageView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_question = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int item_tour = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int item_tournament = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LastAddedTournamentsView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int QuestionsView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int QuestionView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RandomQuestionsView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SplashScreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TourView = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menuitem = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int question = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int ActionBar_Chgk = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int Button_Chgk = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int ChGK_Theme = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int ExpandableListView_Chgk = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int ListView_Chgk = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int ProgressBar_ChGK = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public const int MvxListView_GroupItemTemplate = 1;
			
			// aapt resource value: 2
			public const int MvxListView_MvxDropDownItemTemplate = 2;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
